project: 
  type: website

website:
  title: "Maia Faith Chambers - Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  site-url: https://MFChambers.github.io/MFC-fr/
  repo-url: https://github.com/MFChambers/MFC-fr
  issue-url: https://github.com/MFChambers/MFC-fr/issues/new
  repo-actions: [issue]

  page-footer: 
    border: true
    left: "Maia_Chambers 2025©"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/maia-chambers/

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "DS250 Projects"
        file: 250_projects.qmd

  sidebar:
    - title: "DS 250 Projects"
      style: "docked"
      background: light
      contents:
        - text: "DS250 Projects"
          file: 250_projects.qmd
        - text: "---"
        - text: "Project 1"
          file: 250_Projects/project1.qmd
        - text: "Project 2"
          file: 250_Projects/project2.qmd
        - text: "Project 3"
          file: 250_Projects/project3.qmd
        - text: "Project 4"
          file: 250_Projects/project4.qmd
        - text: "Project 5"
          file: 250_Projects/project5.qmd
        - text: "---"

format:  
  html:
    theme:
      light: [flatly, theme.scss]       # light mode (customizable)
      dark: [darkly, theme-dark.scss]   # dark mode (fully customized)
    css: styles.css                     # optional custom tweaks
    toc: true
    code-copy: true
    respect-user-color-scheme: true
    toc-depth: 2
    toc-title: "Table of Contents"
    toc-show: true
    toc-float: true
    toc-float-offset: 100
    toc-float-width: 300
    toc-float-position: right
    toc-float-breakpoint: 768
    toc-float-scroll: true
    toc-float-scroll-offset: 50
    toc-float-scroll-duration: 300
    toc-float-scroll-easing: ease-in-out
    toc-float-scroll-target: "#toc"

include-in-header:
  - text: |
      <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">