on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true 
      
      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install jupyter numpy pandas scikit-learn lets-plot palmerpenguins nbformat nbclient tabulate skimpy seaborn matplotlib kaleido graphviz xgboost
      - name: Install Graphviz system tool
        run: sudo apt-get update && sudo apt-get install -y graphviz

      # R setup (commented out)
      # - name: Install R
      #   uses: r-lib/actions/setup-r@v2
      #   with:
      #     use-public-rspm: true

      # - name: Install R Dependencies
      #   uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     packages: 
      #       any::tidyverse
      #       any::knitr
      #       any::DT

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
